receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
exporters:
  postgresexporter:
    connectionString: "postgrs://postgres:postgres@localhost:5432/postgres" 
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ postgresexporter ]
    logs:
      receivers: [ otlp ]
      exporters: [ postgresexporter ]
    metrics:
      receivers: [ otlp ]
      exporters: [ postgresexporter ]